"base_path": "Translation"
"export_languages": [
    "ja"
  ]
"pull_request_title": "Pull Request: 翻訳アップデート"
"pull_request_labels": [
  "crowdin",
  "l10n"
]
"commit_message": "Update: Crowdinで更新された%two_letters_code%の%original_file_name%ファイルを更新"
"append_commit_message": false

files:
  - source: '*xlsx'
    translation: '%original_file_name%'
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'source_phrase,ja,zh-CN,zh-TW,en,fr,de,it,ko,pt-PT,pt-BR,ru,es-ES,es-419,tr,cs,da,sv-SE,hu,sk,fi,lt'
